apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-api-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-api-users
  template:
    metadata:
      labels:
        app: fiap-api-users
    spec:
      containers:
        - name: fiap-api-users
          image: fiap-api-users:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: Host=postgres;Port=5432;Database=fhck_users;Username=postgres;Password=postgres123
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-api-users
spec:
  type: NodePort
  selector:
    app: fiap-api-users
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001